name: Deploy Node.js backend to EC2 on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy backend folder to EC2 (to /home/EC2_USER/backend)
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no -r ./backend ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

      - name: Install dependencies and restart app
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/backend
            npm install
            # Kill existing node processes (you can adjust this if needed)
            pkill -f "node index.js" || echo "No node process found"
            # Start the app in background, redirect output (adjust as needed)
            nohup node index.js > app.log 2>&1 &
          EOF

      - name: Clean up private key
        run: rm -f private_key.pem
